# Generated by Django 4.1 on 2022-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100)),
                ('kodu', models.CharField(max_length=10)),
                ('sbkodu', models.CharField(max_length=7)),
                ('kurumadı', models.CharField(max_length=70)),
                ('sehir', models.CharField(max_length=17)),
                ('sayi', models.CharField(max_length=17)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hemsire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100)),
                ('kodu', models.CharField(max_length=10)),
                ('sbkodu', models.CharField(max_length=7)),
                ('kurumadı', models.CharField(max_length=70)),
                ('sehir', models.CharField(max_length=17)),
                ('sayi', models.CharField(max_length=17)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
